create_move_request:
  properties:
    from:
      type: string
      required: true
    to:
      type: string
      required: true

move:
  properties:
    created_at:
      type: datetime
      format: iso8601
      required: true
    from:
      type: string
      required: true
    to:
      type: string
      required: true
    captured:
      type: string
      required: false
    special_type:
      type: string
      required: false
    chessman:
      type: string
      required: false

user:
  properties:
    id:
      type: integer
      required: true
    nickname:
      type: string
      required: false

board:
  properties:
    A8:
      type: string
      required: false
    H1:
      type: string
      required: false

create_game_request:
  properties:
    white_player_id:
      type: integer
      required: true
    black_player_id:
      type: integer
      required: true

game:
  properties:
    id:
      type: integer
      required: true
    created_at:
      type: datetime
      format: iso8601
      required: true
    mate:
      type: boolean
      required: true
    stalemate:
      type: boolean
      required: true
    whose_round:
      type: string
      required: true
    creator:
      type: user
      required: true
    white_player:
      type: user
      required: true
    black_player:
      type: user
      required: true
    board:
      type: board
      required: true
    moves:
      type: array
      required: true
      items:
        type: move
